### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by giammaleoni** [giammaleoni/TestPBo#1]
# Max :hankey:

@maxvaega 
- [x] Gestione mezzi di trasporto diversi
- [x] Gestione notifiche su preferiti
- [x] Marker su Map con macchinina parcheggio attuale
- [x] Sparcheggia deve eliminare il marker
- [x] Preseleziona valore tendina al click su una via nella mappa
- [x] Se selezionata una via nella tendina deve posizionare l'infowindow sulla mappa
- [x] GoogleMap non funziona
- [x] Quando clicchi sulla notifica si apre l'app col popup e sfondo sfocato che ti avvisa di spostare la macchina, due pulsanti (sparcheggia vs ignora)
# Gianma :bowtie:

@giammaleoni
- [x] Wait prima di schedulazione notifiche per vedere che le notifche siano state cancellate
- [x] Gestione notifiche su "popup notifica cliccata"
- [x] Aggiungere pulsante "add to preferiti" nell'infowindow
- [x] Tastoni colorati e piatti
- [x] Eliminare evento on-change tendina
- [x] Disabilitare/abilitare pulsante parcheggio a seconda se auto parcheggiata
- [x] Disabilitare abilitare pulsante lista giornate a seconda se auto parcheggiata
- [x] Pulire div lista giornate se auto sparcheggiata
- [x] Pan to Current position
- [x] Cancellare contoller mappa (parcheggio/add to preferiti)
- [x] Mettere swipe al posto di flip sulle pagine
- [x] Sfondo per app
- [x] Pagina preferiti non funzionante su mobile

![mock up](https://cloud.githubusercontent.com/assets/12344105/8019442/4dd4441c-0c4e-11e5-978b-425ed9b4a760.jpeg)
